train_data_path: data/processed/train_ubend3888.csv
val_data_path: data/processed/val_ubend3888.csv
normalized_data_path: data/processed/norm_ubend3888.csv
experiment_name: train_baselines
model_info_dir: models/baseline
